// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: grpc/runtime.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_ALL              EventType = 0
	EventType_STATE_CHANGES    EventType = 1
	EventType_ACTION_EXECUTION EventType = 2
	EventType_GOAL_LIFECYCLE   EventType = 3
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "ALL",
		1: "STATE_CHANGES",
		2: "ACTION_EXECUTION",
		3: "GOAL_LIFECYCLE",
	}
	EventType_value = map[string]int32{
		"ALL":              0,
		"STATE_CHANGES":    1,
		"ACTION_EXECUTION": 2,
		"GOAL_LIFECYCLE":   3,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_runtime_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_grpc_runtime_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_runtime_proto_rawDescGZIP(), []int{0}
}

type GoalStatus int32

const (
	GoalStatus_PENDING   GoalStatus = 0
	GoalStatus_RUNNING   GoalStatus = 1
	GoalStatus_COMPLETED GoalStatus = 2
	GoalStatus_FAILED    GoalStatus = 3
	GoalStatus_CANCELLED GoalStatus = 4
	GoalStatus_PAUSED    GoalStatus = 5
)

// Enum value maps for GoalStatus.
var (
	GoalStatus_name = map[int32]string{
		0: "PENDING",
		1: "RUNNING",
		2: "COMPLETED",
		3: "FAILED",
		4: "CANCELLED",
		5: "PAUSED",
	}
	GoalStatus_value = map[string]int32{
		"PENDING":   0,
		"RUNNING":   1,
		"COMPLETED": 2,
		"FAILED":    3,
		"CANCELLED": 4,
		"PAUSED":    5,
	}
)

func (x GoalStatus) Enum() *GoalStatus {
	p := new(GoalStatus)
	*p = x
	return p
}

func (x GoalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GoalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_runtime_proto_enumTypes[1].Descriptor()
}

func (GoalStatus) Type() protoreflect.EnumType {
	return &file_grpc_runtime_proto_enumTypes[1]
}

func (x GoalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GoalStatus.Descriptor instead.
func (GoalStatus) EnumDescriptor() ([]byte, []int) {
	return file_grpc_runtime_proto_rawDescGZIP(), []int{1}
}

type SubmitGoalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Definition    string                 `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitGoalRequest) Reset() {
	*x = SubmitGoalRequest{}
	mi := &file_grpc_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitGoalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitGoalRequest) ProtoMessage() {}

func (x *SubmitGoalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitGoalRequest.ProtoReflect.Descriptor instead.
func (*SubmitGoalRequest) Descriptor() ([]byte, []int) {
	return file_grpc_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitGoalRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubmitGoalRequest) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *SubmitGoalRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SubmitGoalRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type SubmitGoalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoalId        string                 `protobuf:"bytes,1,opt,name=goal_id,json=goalId,proto3" json:"goal_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitGoalResponse) Reset() {
	*x = SubmitGoalResponse{}
	mi := &file_grpc_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitGoalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitGoalResponse) ProtoMessage() {}

func (x *SubmitGoalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitGoalResponse.ProtoReflect.Descriptor instead.
func (*SubmitGoalResponse) Descriptor() ([]byte, []int) {
	return file_grpc_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitGoalResponse) GetGoalId() string {
	if x != nil {
		return x.GoalId
	}
	return ""
}

func (x *SubmitGoalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitGoalResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetGoalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoalId        string                 `protobuf:"bytes,1,opt,name=goal_id,json=goalId,proto3" json:"goal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoalRequest) Reset() {
	*x = GetGoalRequest{}
	mi := &file_grpc_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoalRequest) ProtoMessage() {}

func (x *GetGoalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoalRequest.ProtoReflect.Descriptor instead.
func (*GetGoalRequest) Descriptor() ([]byte, []int) {
	return file_grpc_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *GetGoalRequest) GetGoalId() string {
	if x != nil {
		return x.GoalId
	}
	return ""
}

type GetGoalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goal          *Goal                  `protobuf:"bytes,1,opt,name=goal,proto3" json:"goal,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoalResponse) Reset() {
	*x = GetGoalResponse{}
	mi := &file_grpc_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoalResponse) ProtoMessage() {}

func (x *GetGoalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoalResponse.ProtoReflect.Descriptor instead.
func (*GetGoalResponse) Descriptor() ([]byte, []int) {
	return file_grpc_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *GetGoalResponse) GetGoal() *Goal {
	if x != nil {
		return x.Goal
	}
	return nil
}

func (x *GetGoalResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListGoalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        GoalStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=grpc.GoalStatus" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGoalsRequest) Reset() {
	*x = ListGoalsRequest{}
	mi := &file_grpc_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGoalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGoalsRequest) ProtoMessage() {}

func (x *ListGoalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGoalsRequest.ProtoReflect.Descriptor instead.
func (*ListGoalsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *ListGoalsRequest) GetStatus() GoalStatus {
	if x != nil {
		return x.Status
	}
	return GoalStatus_PENDING
}

func (x *ListGoalsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListGoalsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListGoalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goals         []*Goal                `protobuf:"bytes,1,rep,name=goals,proto3" json:"goals,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGoalsResponse) Reset() {
	*x = ListGoalsResponse{}
	mi := &file_grpc_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGoalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGoalsResponse) ProtoMessage() {}

func (x *ListGoalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGoalsResponse.ProtoReflect.Descriptor instead.
func (*ListGoalsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *ListGoalsResponse) GetGoals() []*Goal {
	if x != nil {
		return x.Goals
	}
	return nil
}

func (x *ListGoalsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CancelGoalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoalId        string                 `protobuf:"bytes,1,opt,name=goal_id,json=goalId,proto3" json:"goal_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelGoalRequest) Reset() {
	*x = CancelGoalRequest{}
	mi := &file_grpc_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelGoalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelGoalRequest) ProtoMessage() {}

func (x *CancelGoalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelGoalRequest.ProtoReflect.Descriptor instead.
func (*CancelGoalRequest) Descriptor() ([]byte, []int) {
	return file_grpc_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *CancelGoalRequest) GetGoalId() string {
	if x != nil {
		return x.GoalId
	}
	return ""
}

func (x *CancelGoalRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelGoalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelGoalResponse) Reset() {
	*x = CancelGoalResponse{}
	mi := &file_grpc_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelGoalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelGoalResponse) ProtoMessage() {}

func (x *CancelGoalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelGoalResponse.ProtoReflect.Descriptor instead.
func (*CancelGoalResponse) Descriptor() ([]byte, []int) {
	return file_grpc_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *CancelGoalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelGoalResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoalId        string                 `protobuf:"bytes,1,opt,name=goal_id,json=goalId,proto3" json:"goal_id,omitempty"`
	EventType     EventType              `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=grpc.EventType" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_grpc_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *StreamEventsRequest) GetGoalId() string {
	if x != nil {
		return x.GoalId
	}
	return ""
}

func (x *StreamEventsRequest) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_ALL
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GoalId        string                 `protobuf:"bytes,2,opt,name=goal_id,json=goalId,proto3" json:"goal_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type          EventType              `protobuf:"varint,4,opt,name=type,proto3,enum=grpc.EventType" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_grpc_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_grpc_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetGoalId() string {
	if x != nil {
		return x.GoalId
	}
	return ""
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_ALL
}

func (x *Event) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoalId        string                 `protobuf:"bytes,1,opt,name=goal_id,json=goalId,proto3" json:"goal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_grpc_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *GetMetricsRequest) GetGoalId() string {
	if x != nil {
		return x.GoalId
	}
	return ""
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *Metrics               `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_grpc_runtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_runtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *GetMetricsResponse) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_grpc_runtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_runtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_grpc_runtime_proto_rawDescGZIP(), []int{12}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Uptime        int64                  `protobuf:"varint,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_grpc_runtime_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_runtime_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_grpc_runtime_proto_rawDescGZIP(), []int{13}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

type Goal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Definition    string                 `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"`
	Status        GoalStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=grpc.GoalStatus" json:"status,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Deadline      int64                  `protobuf:"varint,8,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Dependencies  []string               `protobuf:"bytes,10,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	Error         string                 `protobuf:"bytes,11,opt,name=error,proto3" json:"error,omitempty"`
	RetryCount    int32                  `protobuf:"varint,12,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Goal) Reset() {
	*x = Goal{}
	mi := &file_grpc_runtime_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goal) ProtoMessage() {}

func (x *Goal) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_runtime_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goal.ProtoReflect.Descriptor instead.
func (*Goal) Descriptor() ([]byte, []int) {
	return file_grpc_runtime_proto_rawDescGZIP(), []int{14}
}

func (x *Goal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Goal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Goal) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *Goal) GetStatus() GoalStatus {
	if x != nil {
		return x.Status
	}
	return GoalStatus_PENDING
}

func (x *Goal) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Goal) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Goal) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Goal) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *Goal) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Goal) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *Goal) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Goal) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

type Metrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalGoals         int64                  `protobuf:"varint,1,opt,name=total_goals,json=totalGoals,proto3" json:"total_goals,omitempty"`
	ActiveGoals        int64                  `protobuf:"varint,2,opt,name=active_goals,json=activeGoals,proto3" json:"active_goals,omitempty"`
	CompletedGoals     int64                  `protobuf:"varint,3,opt,name=completed_goals,json=completedGoals,proto3" json:"completed_goals,omitempty"`
	FailedGoals        int64                  `protobuf:"varint,4,opt,name=failed_goals,json=failedGoals,proto3" json:"failed_goals,omitempty"`
	ActionsExecuted    int64                  `protobuf:"varint,5,opt,name=actions_executed,json=actionsExecuted,proto3" json:"actions_executed,omitempty"`
	AvgExecutionTimeMs float64                `protobuf:"fixed64,6,opt,name=avg_execution_time_ms,json=avgExecutionTimeMs,proto3" json:"avg_execution_time_ms,omitempty"`
	MemoryUsageBytes   int64                  `protobuf:"varint,7,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_grpc_runtime_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_runtime_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_grpc_runtime_proto_rawDescGZIP(), []int{15}
}

func (x *Metrics) GetTotalGoals() int64 {
	if x != nil {
		return x.TotalGoals
	}
	return 0
}

func (x *Metrics) GetActiveGoals() int64 {
	if x != nil {
		return x.ActiveGoals
	}
	return 0
}

func (x *Metrics) GetCompletedGoals() int64 {
	if x != nil {
		return x.CompletedGoals
	}
	return 0
}

func (x *Metrics) GetFailedGoals() int64 {
	if x != nil {
		return x.FailedGoals
	}
	return 0
}

func (x *Metrics) GetActionsExecuted() int64 {
	if x != nil {
		return x.ActionsExecuted
	}
	return 0
}

func (x *Metrics) GetAvgExecutionTimeMs() float64 {
	if x != nil {
		return x.AvgExecutionTimeMs
	}
	return 0
}

func (x *Metrics) GetMemoryUsageBytes() int64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

var File_grpc_runtime_proto protoreflect.FileDescriptor

const file_grpc_runtime_proto_rawDesc = "" +
	"\n" +
	"\x12grpc/runtime.proto\x12\x04grpc\"\xe3\x01\n" +
	"\x11SubmitGoalRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"definition\x18\x02 \x01(\tR\n" +
	"definition\x12A\n" +
	"\bmetadata\x18\x03 \x03(\v2%.grpc.SubmitGoalRequest.MetadataEntryR\bmetadata\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x12SubmitGoalResponse\x12\x17\n" +
	"\agoal_id\x18\x01 \x01(\tR\x06goalId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\")\n" +
	"\x0eGetGoalRequest\x12\x17\n" +
	"\agoal_id\x18\x01 \x01(\tR\x06goalId\"G\n" +
	"\x0fGetGoalResponse\x12\x1e\n" +
	"\x04goal\x18\x01 \x01(\v2\n" +
	".grpc.GoalR\x04goal\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"j\n" +
	"\x10ListGoalsRequest\x12(\n" +
	"\x06status\x18\x01 \x01(\x0e2\x10.grpc.GoalStatusR\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"K\n" +
	"\x11ListGoalsResponse\x12 \n" +
	"\x05goals\x18\x01 \x03(\v2\n" +
	".grpc.GoalR\x05goals\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"D\n" +
	"\x11CancelGoalRequest\x12\x17\n" +
	"\agoal_id\x18\x01 \x01(\tR\x06goalId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"D\n" +
	"\x12CancelGoalResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"^\n" +
	"\x13StreamEventsRequest\x12\x17\n" +
	"\agoal_id\x18\x01 \x01(\tR\x06goalId\x12.\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2\x0f.grpc.EventTypeR\teventType\"\x8d\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\agoal_id\x18\x02 \x01(\tR\x06goalId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12#\n" +
	"\x04type\x18\x04 \x01(\x0e2\x0f.grpc.EventTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayload\",\n" +
	"\x11GetMetricsRequest\x12\x17\n" +
	"\agoal_id\x18\x01 \x01(\tR\x06goalId\"=\n" +
	"\x12GetMetricsResponse\x12'\n" +
	"\ametrics\x18\x01 \x01(\v2\r.grpc.MetricsR\ametrics\"\x14\n" +
	"\x12HealthCheckRequest\"a\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\x03R\x06uptime\"\xb8\x03\n" +
	"\x04Goal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"definition\x18\x03 \x01(\tR\n" +
	"definition\x12(\n" +
	"\x06status\x18\x04 \x01(\x0e2\x10.grpc.GoalStatusR\x06status\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\x12\x1a\n" +
	"\bdeadline\x18\b \x01(\x03R\bdeadline\x124\n" +
	"\bmetadata\x18\t \x03(\v2\x18.grpc.Goal.MetadataEntryR\bmetadata\x12\"\n" +
	"\fdependencies\x18\n" +
	" \x03(\tR\fdependencies\x12\x14\n" +
	"\x05error\x18\v \x01(\tR\x05error\x12\x1f\n" +
	"\vretry_count\x18\f \x01(\x05R\n" +
	"retryCount\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa5\x02\n" +
	"\aMetrics\x12\x1f\n" +
	"\vtotal_goals\x18\x01 \x01(\x03R\n" +
	"totalGoals\x12!\n" +
	"\factive_goals\x18\x02 \x01(\x03R\vactiveGoals\x12'\n" +
	"\x0fcompleted_goals\x18\x03 \x01(\x03R\x0ecompletedGoals\x12!\n" +
	"\ffailed_goals\x18\x04 \x01(\x03R\vfailedGoals\x12)\n" +
	"\x10actions_executed\x18\x05 \x01(\x03R\x0factionsExecuted\x121\n" +
	"\x15avg_execution_time_ms\x18\x06 \x01(\x01R\x12avgExecutionTimeMs\x12,\n" +
	"\x12memory_usage_bytes\x18\a \x01(\x03R\x10memoryUsageBytes*Q\n" +
	"\tEventType\x12\a\n" +
	"\x03ALL\x10\x00\x12\x11\n" +
	"\rSTATE_CHANGES\x10\x01\x12\x14\n" +
	"\x10ACTION_EXECUTION\x10\x02\x12\x12\n" +
	"\x0eGOAL_LIFECYCLE\x10\x03*\\\n" +
	"\n" +
	"GoalStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\r\n" +
	"\tCANCELLED\x10\x04\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x052\xc4\x03\n" +
	"\vGoalRuntime\x12?\n" +
	"\n" +
	"SubmitGoal\x12\x17.grpc.SubmitGoalRequest\x1a\x18.grpc.SubmitGoalResponse\x126\n" +
	"\aGetGoal\x12\x14.grpc.GetGoalRequest\x1a\x15.grpc.GetGoalResponse\x12<\n" +
	"\tListGoals\x12\x16.grpc.ListGoalsRequest\x1a\x17.grpc.ListGoalsResponse\x12?\n" +
	"\n" +
	"CancelGoal\x12\x17.grpc.CancelGoalRequest\x1a\x18.grpc.CancelGoalResponse\x128\n" +
	"\fStreamEvents\x12\x19.grpc.StreamEventsRequest\x1a\v.grpc.Event0\x01\x12?\n" +
	"\n" +
	"GetMetrics\x12\x17.grpc.GetMetricsRequest\x1a\x18.grpc.GetMetricsResponse\x12B\n" +
	"\vHealthCheck\x12\x18.grpc.HealthCheckRequest\x1a\x19.grpc.HealthCheckResponseB\x1dZ\x1bgithub.com/goalruntime/grpcb\x06proto3"

var (
	file_grpc_runtime_proto_rawDescOnce sync.Once
	file_grpc_runtime_proto_rawDescData []byte
)

func file_grpc_runtime_proto_rawDescGZIP() []byte {
	file_grpc_runtime_proto_rawDescOnce.Do(func() {
		file_grpc_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_runtime_proto_rawDesc), len(file_grpc_runtime_proto_rawDesc)))
	})
	return file_grpc_runtime_proto_rawDescData
}

var file_grpc_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_grpc_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_grpc_runtime_proto_goTypes = []any{
	(EventType)(0),              // 0: grpc.EventType
	(GoalStatus)(0),             // 1: grpc.GoalStatus
	(*SubmitGoalRequest)(nil),   // 2: grpc.SubmitGoalRequest
	(*SubmitGoalResponse)(nil),  // 3: grpc.SubmitGoalResponse
	(*GetGoalRequest)(nil),      // 4: grpc.GetGoalRequest
	(*GetGoalResponse)(nil),     // 5: grpc.GetGoalResponse
	(*ListGoalsRequest)(nil),    // 6: grpc.ListGoalsRequest
	(*ListGoalsResponse)(nil),   // 7: grpc.ListGoalsResponse
	(*CancelGoalRequest)(nil),   // 8: grpc.CancelGoalRequest
	(*CancelGoalResponse)(nil),  // 9: grpc.CancelGoalResponse
	(*StreamEventsRequest)(nil), // 10: grpc.StreamEventsRequest
	(*Event)(nil),               // 11: grpc.Event
	(*GetMetricsRequest)(nil),   // 12: grpc.GetMetricsRequest
	(*GetMetricsResponse)(nil),  // 13: grpc.GetMetricsResponse
	(*HealthCheckRequest)(nil),  // 14: grpc.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 15: grpc.HealthCheckResponse
	(*Goal)(nil),                // 16: grpc.Goal
	(*Metrics)(nil),             // 17: grpc.Metrics
	nil,                         // 18: grpc.SubmitGoalRequest.MetadataEntry
	nil,                         // 19: grpc.Goal.MetadataEntry
}
var file_grpc_runtime_proto_depIdxs = []int32{
	18, // 0: grpc.SubmitGoalRequest.metadata:type_name -> grpc.SubmitGoalRequest.MetadataEntry
	16, // 1: grpc.GetGoalResponse.goal:type_name -> grpc.Goal
	1,  // 2: grpc.ListGoalsRequest.status:type_name -> grpc.GoalStatus
	16, // 3: grpc.ListGoalsResponse.goals:type_name -> grpc.Goal
	0,  // 4: grpc.StreamEventsRequest.event_type:type_name -> grpc.EventType
	0,  // 5: grpc.Event.type:type_name -> grpc.EventType
	17, // 6: grpc.GetMetricsResponse.metrics:type_name -> grpc.Metrics
	1,  // 7: grpc.Goal.status:type_name -> grpc.GoalStatus
	19, // 8: grpc.Goal.metadata:type_name -> grpc.Goal.MetadataEntry
	2,  // 9: grpc.GoalRuntime.SubmitGoal:input_type -> grpc.SubmitGoalRequest
	4,  // 10: grpc.GoalRuntime.GetGoal:input_type -> grpc.GetGoalRequest
	6,  // 11: grpc.GoalRuntime.ListGoals:input_type -> grpc.ListGoalsRequest
	8,  // 12: grpc.GoalRuntime.CancelGoal:input_type -> grpc.CancelGoalRequest
	10, // 13: grpc.GoalRuntime.StreamEvents:input_type -> grpc.StreamEventsRequest
	12, // 14: grpc.GoalRuntime.GetMetrics:input_type -> grpc.GetMetricsRequest
	14, // 15: grpc.GoalRuntime.HealthCheck:input_type -> grpc.HealthCheckRequest
	3,  // 16: grpc.GoalRuntime.SubmitGoal:output_type -> grpc.SubmitGoalResponse
	5,  // 17: grpc.GoalRuntime.GetGoal:output_type -> grpc.GetGoalResponse
	7,  // 18: grpc.GoalRuntime.ListGoals:output_type -> grpc.ListGoalsResponse
	9,  // 19: grpc.GoalRuntime.CancelGoal:output_type -> grpc.CancelGoalResponse
	11, // 20: grpc.GoalRuntime.StreamEvents:output_type -> grpc.Event
	13, // 21: grpc.GoalRuntime.GetMetrics:output_type -> grpc.GetMetricsResponse
	15, // 22: grpc.GoalRuntime.HealthCheck:output_type -> grpc.HealthCheckResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_grpc_runtime_proto_init() }
func file_grpc_runtime_proto_init() {
	if File_grpc_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_runtime_proto_rawDesc), len(file_grpc_runtime_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_runtime_proto_goTypes,
		DependencyIndexes: file_grpc_runtime_proto_depIdxs,
		EnumInfos:         file_grpc_runtime_proto_enumTypes,
		MessageInfos:      file_grpc_runtime_proto_msgTypes,
	}.Build()
	File_grpc_runtime_proto = out.File
	file_grpc_runtime_proto_goTypes = nil
	file_grpc_runtime_proto_depIdxs = nil
}
