// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: grpc/runtime.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoalRuntime_SubmitGoal_FullMethodName   = "/grpc.GoalRuntime/SubmitGoal"
	GoalRuntime_GetGoal_FullMethodName      = "/grpc.GoalRuntime/GetGoal"
	GoalRuntime_ListGoals_FullMethodName    = "/grpc.GoalRuntime/ListGoals"
	GoalRuntime_CancelGoal_FullMethodName   = "/grpc.GoalRuntime/CancelGoal"
	GoalRuntime_StreamEvents_FullMethodName = "/grpc.GoalRuntime/StreamEvents"
	GoalRuntime_GetMetrics_FullMethodName   = "/grpc.GoalRuntime/GetMetrics"
	GoalRuntime_HealthCheck_FullMethodName  = "/grpc.GoalRuntime/HealthCheck"
)

// GoalRuntimeClient is the client API for GoalRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoalRuntimeClient interface {
	SubmitGoal(ctx context.Context, in *SubmitGoalRequest, opts ...grpc.CallOption) (*SubmitGoalResponse, error)
	GetGoal(ctx context.Context, in *GetGoalRequest, opts ...grpc.CallOption) (*GetGoalResponse, error)
	ListGoals(ctx context.Context, in *ListGoalsRequest, opts ...grpc.CallOption) (*ListGoalsResponse, error)
	CancelGoal(ctx context.Context, in *CancelGoalRequest, opts ...grpc.CallOption) (*CancelGoalResponse, error)
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type goalRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewGoalRuntimeClient(cc grpc.ClientConnInterface) GoalRuntimeClient {
	return &goalRuntimeClient{cc}
}

func (c *goalRuntimeClient) SubmitGoal(ctx context.Context, in *SubmitGoalRequest, opts ...grpc.CallOption) (*SubmitGoalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitGoalResponse)
	err := c.cc.Invoke(ctx, GoalRuntime_SubmitGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalRuntimeClient) GetGoal(ctx context.Context, in *GetGoalRequest, opts ...grpc.CallOption) (*GetGoalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGoalResponse)
	err := c.cc.Invoke(ctx, GoalRuntime_GetGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalRuntimeClient) ListGoals(ctx context.Context, in *ListGoalsRequest, opts ...grpc.CallOption) (*ListGoalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGoalsResponse)
	err := c.cc.Invoke(ctx, GoalRuntime_ListGoals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalRuntimeClient) CancelGoal(ctx context.Context, in *CancelGoalRequest, opts ...grpc.CallOption) (*CancelGoalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelGoalResponse)
	err := c.cc.Invoke(ctx, GoalRuntime_CancelGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalRuntimeClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GoalRuntime_ServiceDesc.Streams[0], GoalRuntime_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoalRuntime_StreamEventsClient = grpc.ServerStreamingClient[Event]

func (c *goalRuntimeClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, GoalRuntime_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalRuntimeClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, GoalRuntime_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoalRuntimeServer is the server API for GoalRuntime service.
// All implementations must embed UnimplementedGoalRuntimeServer
// for forward compatibility.
type GoalRuntimeServer interface {
	SubmitGoal(context.Context, *SubmitGoalRequest) (*SubmitGoalResponse, error)
	GetGoal(context.Context, *GetGoalRequest) (*GetGoalResponse, error)
	ListGoals(context.Context, *ListGoalsRequest) (*ListGoalsResponse, error)
	CancelGoal(context.Context, *CancelGoalRequest) (*CancelGoalResponse, error)
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[Event]) error
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedGoalRuntimeServer()
}

// UnimplementedGoalRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoalRuntimeServer struct{}

func (UnimplementedGoalRuntimeServer) SubmitGoal(context.Context, *SubmitGoalRequest) (*SubmitGoalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitGoal not implemented")
}
func (UnimplementedGoalRuntimeServer) GetGoal(context.Context, *GetGoalRequest) (*GetGoalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGoal not implemented")
}
func (UnimplementedGoalRuntimeServer) ListGoals(context.Context, *ListGoalsRequest) (*ListGoalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGoals not implemented")
}
func (UnimplementedGoalRuntimeServer) CancelGoal(context.Context, *CancelGoalRequest) (*CancelGoalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelGoal not implemented")
}
func (UnimplementedGoalRuntimeServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedGoalRuntimeServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedGoalRuntimeServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedGoalRuntimeServer) mustEmbedUnimplementedGoalRuntimeServer() {}
func (UnimplementedGoalRuntimeServer) testEmbeddedByValue()                     {}

// UnsafeGoalRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoalRuntimeServer will
// result in compilation errors.
type UnsafeGoalRuntimeServer interface {
	mustEmbedUnimplementedGoalRuntimeServer()
}

func RegisterGoalRuntimeServer(s grpc.ServiceRegistrar, srv GoalRuntimeServer) {
	// If the following call panics, it indicates UnimplementedGoalRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoalRuntime_ServiceDesc, srv)
}

func _GoalRuntime_SubmitGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalRuntimeServer).SubmitGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoalRuntime_SubmitGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalRuntimeServer).SubmitGoal(ctx, req.(*SubmitGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalRuntime_GetGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalRuntimeServer).GetGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoalRuntime_GetGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalRuntimeServer).GetGoal(ctx, req.(*GetGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalRuntime_ListGoals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGoalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalRuntimeServer).ListGoals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoalRuntime_ListGoals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalRuntimeServer).ListGoals(ctx, req.(*ListGoalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalRuntime_CancelGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalRuntimeServer).CancelGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoalRuntime_CancelGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalRuntimeServer).CancelGoal(ctx, req.(*CancelGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalRuntime_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoalRuntimeServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoalRuntime_StreamEventsServer = grpc.ServerStreamingServer[Event]

func _GoalRuntime_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalRuntimeServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoalRuntime_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalRuntimeServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalRuntime_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalRuntimeServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoalRuntime_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalRuntimeServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoalRuntime_ServiceDesc is the grpc.ServiceDesc for GoalRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoalRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.GoalRuntime",
	HandlerType: (*GoalRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitGoal",
			Handler:    _GoalRuntime_SubmitGoal_Handler,
		},
		{
			MethodName: "GetGoal",
			Handler:    _GoalRuntime_GetGoal_Handler,
		},
		{
			MethodName: "ListGoals",
			Handler:    _GoalRuntime_ListGoals_Handler,
		},
		{
			MethodName: "CancelGoal",
			Handler:    _GoalRuntime_CancelGoal_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _GoalRuntime_GetMetrics_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _GoalRuntime_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _GoalRuntime_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc/runtime.proto",
}
